# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  pull_request_target:

permissions:
  contents: write
  pull-requests: write

env:
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"

      - name: make ci
        run: |
          make ci
          
